### ISSUE TITLE
hunter可以添加多个key循环使用吗？

### ISSUE THREAD

**Issue by panzhen1992** [thinkoaa/Deadpool#1]
hunter免费版注册多个账号，每个账号500积分，可以添加多个key循环使用，方便白嫖

<img width="958" alt="image" src="https://github.com/user-attachments/assets/a227abe5-1fde-444b-a451-4ed5cd34d73d">

**Comment by thinkoaa** [comment]
这个问题，本质上是quake、fofa、hunter等积分不够（可能是没买到终身会员导致当前周期积分较少或是终身会员当前周期内的积分用尽。）这个问题可以参考[https://github.com/thinkoaa/Deadpool/issues/3#issuecomment-2320175157](url)，通过其他方式收集代理，放入lastData.txt中，或使用过程中在新的积分生效时，再去获取，不断积累有效代理。

**Comment by panzhen1992** [comment]
好的，感谢大佬
