### ISSUE TITLE
怎么时时动态获取？

### ISSUE THREAD

**Issue by panzhen1992** [thinkoaa/Deadpool#3]

**Comment by thinkoaa** [comment]
根据已经配置的语法，当次使用工具过程中，资产测绘空间最新的数据不一定有什么大的变化，定时去获取意义不大，比较推荐的操作是，第一次启用各资产测绘收集到一些代理后，关闭资产测绘开关，就使用lastData.txt中的即可，或第二天（下次使用时），再执行，各资产测绘平台数据可能是当日的更新。另外，通过别的方式收集的socks5代理也可以不断收集放进lastData.txt中。

**Comment by panzhen1992** [comment]
别的方式收集到的socks5代理，放入lastData.txt中，使用前会先检测存活性吗

**Comment by thinkoaa** [comment]
会检测的，每次工具使用的代理，都会存入lastData中，下次启动从里面再读取出来，用配置文件中的配置，进行检测

**Comment by panzhen1992** [comment]
好的，谢谢

**Comment by thinkoaa** [comment]
> 好的，谢谢

客气，不过需要注意，里面必须是socks5代理，其他代理会检测不通过，不使用的。

**Comment by panzhen1992** [comment]
感谢大佬
