### ISSUE TITLE
一点想法

### ISSUE THREAD

**Issue by N0el4kLs** [thinkoaa/Deadpool#4]
感谢师傅提供的工具🙏。
关于该工具的一点想法，算是一个enhance：
可以给该项目加上一个action, 让该项目可以每隔一段时间(3天或5天/根据需要自定义)自动从网络空间引擎中拉去附和条件的地址并更新到lastData.txt 。这样每当需要使用直接 clone 下来就好。这样更适合（私有化）使用。
缺点：可能对api消耗比较的大

**Comment by thinkoaa** [comment]
这个工具目前的使用场景是，临时需要用代理的时候，使用者配置自己的key，本机去取数据来用，项目本身不提供发布代理数据。不过使用者如果自己想用自己的key定时去取数据，可以改下代码，或者本机做个计划任务每天某个时刻调用脚本去执行一下，这样lastData.txt中就可以不断积累可用代理。

**Comment by thinkoaa** [comment]
(^_^)

**Comment by N0el4kLs** [comment]
🙏
